spring.application.name=CourseManagementSystem


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/db_cms
spring.datasource.username=postgres
spring.datasource.password=1

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=abcdefghijklmnopqrstuvwxyz12345678901234567890
jwt.expiration=86400000
jwt.refresh-expiration=604800000
jwt.verify-expiration=86400000

# Pagination config
app.pagination.default-page=1
app.pagination.default-size=10
app.pagination.max-size=100



